version: "3.7"
services:
  mysql-service:
    image: mysql8
    networks:
     - algafood-api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: algafood      
      MYSQL_USER: root
      MYSQL_PASSWORD: 
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - algafood-api
    depends_on:
      - algafood
networks:
  spring-boot-mysql-network:
    driver: bridge